apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-prometheus-service
  labels:
    {{- include "helm.promlabels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "helm.promlabels" . | nindent 4 }}
